from panda3d.core import BitMask32

FRICTION = 150.0

MASK_ZERO = BitMask32(0x0)
MASK_NOTHING = MASK_ZERO

MASK_ONE = BitMask32(0x1)
MASK_HERO = MASK_ONE

MASK_TWO = BitMask32(0x2)
MASK_MONSTER = MASK_TWO

MASK_HERO_AND_MONSTER = MASK_ONE | MASK_TWO
